### ISSUE TITLE
404 Not found error while creating new conversation.

### ISSUE THREAD

**Issue by gunpal5** [bsdayo/BingChat#20]
Hi

I am getting this error while trying out the new cli 0.8.0. Is there anyway to get around this issue?

![image](https://github.com/bsdayo/BingChat/assets/10114874/51d3ecc8-6246-4a99-b525-11b25fb09ea3)

**Comment by gunpal5** [comment]
@bsdayo, 

Thank you for quick response. It happens only when you send excessive messages. e.g. run the BingChat client with multiple threads.

**Comment by bsdayo** [comment]
> Is there anyway to use proxies with it?

The easiest way is to set a global proxy, alternatively you can set `HTTP_PROXY` or `HTTPS_PROXY` environment variables.

Maybe we should add a option to control proxy in the future? 🤔

**Comment by 0xlane** [comment]
> @bsdayo,
> 
> Thank you for quick response. It happens only when you send excessive messages. e.g. run the BingChat client with multiple threads.
> 
> Bing seems to block the IP after that.

I have also encountered this situation.

**Comment by matthewj-dev** [comment]
I also encountered this. 

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonTypeInfo`1 jsonTypeInfo, CancellationToken cancellationToken)
         at BingChat.BingChatClient.CreateConversation()
```
