### ISSUE TITLE
CaptchaChallenge: User needs to solve CAPTCHA to continue. 

### ISSUE THREAD

**Issue by hmirheydari** [bsdayo/BingChat#35]
when I run it I receive

BingChat.BingChatException
  HResult=0x80131500
  Message=CaptchaChallenge: User needs to solve CAPTCHA to continue.
  Source=BingChat
  StackTrace:
   at BingChat.BingChatConversation.BuildAnswer(ChatResponse response)
   at BingChat.BingChatConversation.<AskAsync>d__5.MoveNext()
   at BingChat.BingChatConversation.<AskAsync>d__5.MoveNext()
   at BingChat.BingChatClient.<AskAsync>d__3.MoveNext()
   at BingChat_test.Program.<Main>d__0.MoveNext() in C:\Users\Kevin\source\repos\BingChat-test\Program.cs:line 19
   at BingChat_test.Program.<Main>(String[] args)

**Comment by hmirheydari** [comment]
I have copied the working cookie from MS Edge but it have the same problem

**Comment by hswlab** [comment]
It seems that without a cookie, the captcha error message now always comes up, even if there are no captchas to solve in the Edge browser.  With a new cookie token, however, the request still seems to work without an error message. I hope there will be a solution for this captcha problem. It was nice to be able to use the chat without having to copy any strings from the browser :)

**Comment by Ibrahim-teyim** [comment]
I have the same issue, is there a work-around to this?

**Comment by hswlab** [comment]
I noticed that when you are not logged in there is no _U cookie. Maybe something has changed in the way of communication with a guest account. But I don't know well enough to say what exactly has changed and how to fix it :)

**Comment by 42Entwickler** [comment]
Worked for me: Log in to your browser. Use the cookie-value and ask one simple question or simply type HI to bing. Then the verification is done and the cookie-value works.
So if this error occurs just ensure you have the same cookie-value and say hi to bing - this does the verification.

**Comment by 42Entwickler** [comment]
Hiere is a Tutorial using the nuget package and solving this problem: https://youtu.be/17w5wSBiXkI (sry. German Language)

**Comment by aqibadnare** [comment]
I am facing the same issue. Can we solve this without using Cookie Value and saying Hi to Bing?

**Comment by hmirheydari** [comment]
Hi All,

Unfortunately, I tested it with a fresh token from Edge and the error
remained, I think Microsoft continuously working on it to prevent users
from using it outside of Edge.
