### ISSUE TITLE
Code doesn't work in the CLI

### ISSUE THREAD

**Issue by DmitryBorodiy** [bsdayo/BingChat#4]
System.NullReferenceException: Object reference not set to an instance of an object
   at BingChat.BingChatConversation.<AskAsync>g__GetAnswer|3_1(BingChatConversationResponse response)
   at BingChat.BingChatConversation.<>c__DisplayClass3_0.<AskAsync>g__OnMessageReceived|2(String text)
--- End of stack trace from previous location ---
   at HelloWold.Program.ComposeAnswerAsync(String request)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by bsdayo** [comment]
Seems to be a duplicate of #3. I just left a message there, so you can check it out.
